Introduce symflower-buffile, and add user mode, for quick access to everyday commands
symflower/symflower-kakoune pull request #3
Opened 2022-02-28 11:26 UTC by krobelus

2022-02-28 16:12 UTC, zimmski commented
Usage of the README needs to be adapted, since we now allow unit test skeletons as well

2022-02-28 16:14 UTC, zimmski requested changes

2022-02-28 16:14 UTC, zimmski commented on README.md
> +- The `symflower-buffile` command generates tests for the current buffer's file.
Usage of the README needs to be adapted, since we now allow unit test skeletons as well

2022-02-28 16:14 UTC, zimmski commented on rc/symflower.kak
> +map global symflower a %{: symflower-alternative-file<ret>} -docstring "implementation ←→ Symflower test"
Can you please add a feature section to the README to showcase both the unit test generation and unit test skeleton adding with a GIF and text for the user on what these features are and how to use them

2022-03-08 14:11 UTC, krobelus commented on rc/symflower.kak
> +map global symflower a %{: symflower-alternative-file<ret>} -docstring "implementation ←→ Symflower test"
Added screencasts but no separate feature section yet

2022-10-17 10:00 UTC, merged